#!/bin/bash
echo "🔧 AWS CLI Configuration Helper"
echo "================================"
echo ""
echo "Please run: aws configure"
echo ""
echo "You'll need to enter:"
echo "1. AWS Access Key ID"
echo "2. AWS Secret Access Key"
echo "3. Default region: eu-west-3"
echo "4. Default output format: json"
echo ""
echo "After configuring, run: ./build_and_push.sh"
