# Generated by Django 4.2.25 on 2025-10-31 21:43

import daydo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daydo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='color',
            field=models.CharField(blank=True, help_text='HEX color code (e.g., #FF5733)', max_length=7, validators=[daydo.models.validate_hex_color]),
        ),
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(blank=True, help_text='HEX color code (e.g., #FF5733)', max_length=7, validators=[daydo.models.validate_hex_color]),
        ),
    ]
