# Generated by Django 4.2.25 on 2025-11-05 17:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('daydo', '0003_event_eventassignment_role_task_userrole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.OneToOneField(help_text='The family that owns this shopping list', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to='daydo.family')),
            ],
            options={
                'verbose_name': 'Shopping List',
                'verbose_name_plural': 'Shopping Lists',
                'ordering': ['family__name'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the shopping item', max_length=200)),
                ('checked', models.BooleanField(default=False, help_text='Whether the item has been checked off')),
                ('order', models.IntegerField(default=0, help_text='Display order of the item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopping_list', models.ForeignKey(help_text='The shopping list this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='daydo.shoppinglist')),
            ],
            options={
                'verbose_name': 'Shopping Item',
                'verbose_name_plural': 'Shopping Items',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['shopping_list', 'checked'], name='daydo_shopp_shoppin_e090b3_idx'), models.Index(fields=['shopping_list', 'order'], name='daydo_shopp_shoppin_aa552d_idx')],
            },
        ),
    ]
