# Generated by Django 4.2.25 on 2025-11-05 21:14

from django.db import migrations


class Migration(migrations.Migration):

    # This migration was superseded by 0009_todolist_todotask.
    # It is intentionally kept as a no-op to maintain graph consistency.
    dependencies = [
        ('daydo', '0004_shoppinglist_shoppingitem'),
    ]

    operations = [
    ]
