# Generated by Django 4.2.25 on 2025-11-05 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('daydo', '0004_shoppinglist_shoppingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the todo list', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('is_shared', models.BooleanField(default=True, help_text='Whether the list is shared with family')),
                ('color', models.CharField(blank=True, default='blue', help_text='Color theme for the list', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this todo list', on_delete=django.db.models.deletion.CASCADE, related_name='created_todo_lists', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(help_text='The family that owns this todo list', on_delete=django.db.models.deletion.CASCADE, related_name='todo_lists', to='daydo.family')),
            ],
            options={
                'verbose_name': 'Todo List',
                'verbose_name_plural': 'Todo Lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the task', max_length=200)),
                ('completed', models.BooleanField(default=False, help_text='Whether the task is completed')),
                ('order', models.IntegerField(default=0, help_text='Display order of the task')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('todo_list', models.ForeignKey(help_text='The todo list this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='daydo.todolist')),
            ],
            options={
                'verbose_name': 'Todo Task',
                'verbose_name_plural': 'Todo Tasks',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['todo_list', 'completed'], name='daydo_todot_todo_li_a128ac_idx'), models.Index(fields=['todo_list', 'order'], name='daydo_todot_todo_li_d1a158_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='todolist',
            index=models.Index(fields=['family', 'is_shared'], name='daydo_todol_family__cf977b_idx'),
        ),
        migrations.AddIndex(
            model_name='todolist',
            index=models.Index(fields=['created_by'], name='daydo_todol_created_9383a2_idx'),
        ),
    ]
