# Generated by Django 4.2.25 on 2025-11-06 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('daydo', '0009_todolist_todotask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the note', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Rich text content (HTML)')),
                ('is_shared', models.BooleanField(default=False, help_text='Whether the note is shared with family')),
                ('color', models.CharField(blank=True, default='blue', help_text='Color theme for the note', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this note', on_delete=django.db.models.deletion.CASCADE, related_name='created_notes', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(help_text='The family that owns this note', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='daydo.family')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['family', 'is_shared'], name='daydo_note_family__a1b2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['family', '-updated_at'], name='daydo_note_family__d4e5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_by'], name='daydo_note_created_g7h8i9_idx'),
        ),
    ]

