# Generated by Django 4.2.25 on 2025-11-06 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('daydo', '0010_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharingStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_sharing_live', models.BooleanField(default=False, help_text='Whether location sharing is currently active')),
                ('sharing_type', models.CharField(choices=[('one-time', 'One-Time'), ('temporary', 'Temporary'), ('always', 'Always')], default='one-time', help_text='Type of sharing: one-time, temporary, or always', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When temporary sharing expires (null for always/one-time)', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When sharing was started')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User whose sharing status this is', on_delete=django.db.models.deletion.CASCADE, related_name='sharing_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sharing Status',
                'verbose_name_plural': 'Sharing Statuses',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate (-90 to 90)', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate (-180 to 180)', max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this location was recorded')),
                ('sharing_user', models.ForeignKey(help_text='User who is sharing their location', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='sharingstatus',
            index=models.Index(fields=['user', 'is_sharing_live'], name='daydo_shari_user_is_ae8626_idx'),
        ),
        migrations.AddIndex(
            model_name='sharingstatus',
            index=models.Index(fields=['expires_at'], name='daydo_shari_expires__f7d87a_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['sharing_user', '-timestamp'], name='daydo_locat_sharing_db1f64_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['sharing_user', 'timestamp'], name='daydo_locat_sharing_2ed0b0_idx'),
        ),
    ]
