# Generated by Django 4.2.25 on 2025-11-08 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('daydo', '0011_location_sharingstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name of the geofence', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate (-90 to 90)', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate (-180 to 180)', max_digits=9)),
                ('radius', models.PositiveIntegerField(default=50, editable=False, help_text='Radius in meters (fixed to 50m)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Geofence',
                'verbose_name_plural': 'Geofences',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='location',
            new_name='daydo_locat_sharing_90c7ba_idx',
            old_name='daydo_locat_sharing_db1f64_idx',
        ),
        migrations.RenameIndex(
            model_name='location',
            new_name='daydo_locat_sharing_a4121c_idx',
            old_name='daydo_locat_sharing_2ed0b0_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='daydo_note_family__edf1b4_idx',
            old_name='daydo_note_family__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='daydo_note_family__502ece_idx',
            old_name='daydo_note_family__d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='daydo_note_created_3cef00_idx',
            old_name='daydo_note_created_g7h8i9_idx',
        ),
        migrations.RenameIndex(
            model_name='sharingstatus',
            new_name='daydo_shari_user_id_5fab53_idx',
            old_name='daydo_shari_user_is_ae8626_idx',
        ),
        migrations.RenameIndex(
            model_name='sharingstatus',
            new_name='daydo_shari_expires_bc7840_idx',
            old_name='daydo_shari_expires__f7d87a_idx',
        ),
        migrations.AddField(
            model_name='geofence',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this geofence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_geofences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geofence',
            name='family',
            field=models.ForeignKey(help_text='Family that owns this geofence', on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to='daydo.family'),
        ),
        migrations.AddIndex(
            model_name='geofence',
            index=models.Index(fields=['family', 'name'], name='daydo_geofe_family__265927_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='geofence',
            unique_together={('family', 'name')},
        ),
    ]
