# Generated by Django 4.2.25 on 2025-11-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daydo', '0013_merge_20251108_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='star_count',
            field=models.PositiveIntegerField(default=0, help_text='Accumulated stars from completed tasks'),
        ),
    ]
