# Generated by Django 4.2.25 on 2025-11-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daydo', '0014_add_user_star_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horizontal accuracy in meters', max_digits=7, null=True),
        ),
    ]
